### ISSUE TITLE
Boltzmann constant factor missing in pressure_profile_and_gradient method

### ISSUE THREAD

**Issue by sgibson-mse** [C-bowman/pedestal-inference#1]
Think the pressure calculation should include a factor for the Boltzmann constant potentially?

> pe_grads[smp, :] = te_prof * ne_grad + ne_prof * te_grad

**Comment by C-bowman** [comment]
Thanks @sgibson-mse - I had left it in `eV / m^3` but it's clearer to have it in SI, so I'm converting it to `J / m^3` now.

I've also changed the function docs to specify the units for the electron temperature, density and pressure.
